name: Build Project

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'build.zig'
      - 'build.zig.zon'

env:
  ZIG_VERSION: 0.11.0

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - 'x86_64-windows'
          - 'x86-windows'
          - 'x86_64-macos'
          - 'aarch64-macos'
          - 'x86_64-linux'
          - 'x86-linux'
          - 'arm-linux-gnueabihf'
          - 'aarch64-linux-gnu'
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
      - uses: Hanaasagi/zig-action-cache@master

      - name: Build
        run: zig build -Dtarget=${{ matrix.target }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: telnet-zig-${{ matrix.target }}
          path: zig-out/bin/
