name: Check PR title

on: [pull_request_target]

jobs:
  lint:
    runs-on: ubuntu-22.04
    permissions:
      statuses: write
    steps:
      - uses: aslafy-z/conventional-pr-title-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
